### ISSUE TITLE
IllegalStateException: jsonObject["default-gamemode"] must not be null

### ISSUE THREAD

**Issue by mibby** [Gnat008/perworldinventory-kt#32] opened 2018-05-01 23:09 UTC
PerWorldInventory-KT dev 50

Testing KT version with PWI 1.x files / conversion.
```
[15:37:03] [Server thread/WARN]: [PerWorldInventory] Task #125 for PerWorldInventory v2.0.0 generated an exception
java.lang.IllegalStateException: jsonObject["default-gamemode"] must not be null
	at me.ebonjaeger.perworldinventory.GroupManager$loadGroups$1$$special$$inlined$use$lambda$1.invoke(GroupManager.kt:108) ~[perworldinventory-kt-2.0.0.jar:?]
	at me.ebonjaeger.perworldinventory.GroupManager$loadGroups$1$$special$$inlined$use$lambda$1.invoke(GroupManager.kt:16) ~[perworldinventory-kt-2.0.0.jar:?]
	at me.ebonjaeger.perworldinventory.service.BukkitServiceKt$sam$Runnable$7e5632db.run(BukkitService.kt) ~[perworldinventory-kt-2.0.0.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1410]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) [patched_1.12.2.jar:git-Paper-1410]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [patched_1.12.2.jar:git-Paper-1410]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1410]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1410]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1410]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]

```

**Comment by Gnat008** [comment] 2018-05-02 21:19
As a note, both of your worlds configuration related issues will be resolved with the move back to YAML. Yay beta software! Ugh.

**Comment by Gnat008** [comment] 2018-05-02 23:00
@mibby could you try the latest beta release [here](https://github.com/Gnat008/perworldinventory-kt/releases/tag/v2.0.0-beta.6) and report if the issue is resolved?

**Comment by Gnat008** [comment] 2018-05-07 22:39
Using the latest build, and everything seems to be working fine now.

**Comment by Gnat008** [comment] 2018-05-10 18:59
Going to close this as it indeed seems to work. If this is in error, please re-open the issue.

**Closed by Gnat008** 2018-05-10 18:59 UTC
Labels: Status: Please Verify, Type: Bug

**Comment by mibby** [comment] 2018-05-19 14:31
Apologies for the late reply. Seems to be working without error now. Thanks!
